on: [push]

jobs:
  build:
    runs-on: node20_bullseye
    steps:
      - uses: actions/checkout@v4

      - name: System prepare
        run: |
          apt update
          apt install -y build-essential

      - name: Building
        id: build
        run: |
          VERSION=$(grep -oP '(?<=CXXSPEC_VERSION ")v[0-9\.]+' ./src/cxxspec.hpp)
          echo "Found version: $VERSION"
          echo version="$VERSION" >> $GITHUB_OUTPUT

          CC=g++ CXX=g++ make libcxxspec
          PREFIX=./dist make install
          cd ./dist && tar -cvJf ../cxxspec_$VERSION.tar.xz *

      - uses: actions/upload-artifact@v3
        with:
          name: cxxspec_${{ steps.build.outputs.version }}.tar.xz
          path: ./cxxspec_${{ steps.build.outputs.version }}.tar.xz

      - if: startsWith(github.ref, 'refs/tags/')
        uses: actions/action-gh-release@v2
        with:
          files: |
            cxxspec_${{ steps.build.outputs.version }}.tar.xz
